/* Live UI contract tests. Network is deliberately mocked; never ships mock data into index.html. */
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),results=[],errors=[];
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const configured=html.replace("phase2ApiUrl: '',","phase2ApiUrl: 'https://api.unit.test',").replace('websocketEnabled: true','websocketEnabled: false');
function totp(){const buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=crypto.createHmac('sha1',Buffer.from('12345678901234567890')).update(buf).digest();const i=h[19]&15;return ((h.readUInt32BE(i)&0x7fffffff)%1000000).toString().padStart(6,'0')}
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html; charset=utf-8');r.end(q.url==='/unconfigured'?html:configured)});await new Promise(r=>server.listen(8770,'127.0.0.1',r));const launch={headless:true};if(process.env.CHROMIUM_EXECUTABLE){launch.executablePath=process.env.CHROMIUM_EXECUTABLE;launch.args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu-sandbox'];}const browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
let expirySweep=true;
let stage='none',enrolled=false,failNetwork=false,stale=false,unknownGps=false,wrongMfa=0,imageFailure=false;
let events=[],calls=[],users=[{id:'admin-id',display_name:'مدير العمليات',role:'admin',active:true}];const iso=x=>new Date(x).toISOString();
function add(id,object='boat',status='pending'){const e={event_id:id,mission_id:'MIS-TEST',drone_id:'UAV-01',track_id:7,object,person_visible:null,confidence:.94,latitude:17.119,longitude:42.454,location_validity:'Approximate',drone_latitude:17.123,drone_longitude:42.456,target_accuracy_m:24,location_source:'image_projection',timestamp:iso(Date.now()),received_at:iso(Date.now()),review_started_at:iso(Date.now()),review_expires_at:iso(Date.now()+20000),image_path:'events/test.png',status,version:0};events.unshift(e);return e}
add('EVT-TEST-001');add('EVT-SUSPECT','floating_mine_candidate','rejected');
function telemetry(){return {drone_id:'UAV-01',mission_id:'MIS-TEST',updated_at:iso(Date.now()-(stale?60000:0)),battery_percent:76,battery_voltage_v:15.3,latitude:unknownGps?null:17.123,longitude:unknownGps?null:42.456,home_latitude:17.124,home_longitude:42.452,heading_deg:122,altitude_m:42,speed_mps:6.4,distance_travelled_m:1268,distance_to_home_m:437,gps_fix_type:unknownGps?'no_fix':'3d',gps_satellites:14,gps_hdop:1.1,armed:true,flight_time_s:485,link_quality_percent:92,flight_mode:'GUIDED',connection_type:'4G',signal_dbm:-75}}
const json=(r,data,status=200,headers={})=>r.fulfill({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Expose-Headers':'content-range',...headers},body:JSON.stringify(data)});
await page.route('https://**/*',async r=>{const req=r.request(),u=new URL(req.url()),p=u.pathname;calls.push({p,method:req.method(),hasApiKey:'apikey' in req.headers()});if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'*'}});let body={};try{body=req.postDataJSON()||{}}catch{}
 if(p==='/api/v1/auth/login'){if(body.login_id.toLowerCase()!=='mar-001'||body.password!=='test-password-only')return json(r,{detail:'Invalid'},401);stage='aal1';return json(r,{access_token:'aal1',refresh_token:'refresh1',expires_in:3600,user:{id:'admin-id'}})}
 if(p==='/api/v1/auth/user')return json(r,{id:'admin-id',factors:enrolled?[{id:'factor-1',factor_type:'totp',status:'verified'}]:[]});
 if(p==='/api/v1/auth/factors'&&req.method()==='POST')return json(r,{id:'factor-1',totp:{secret:'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',qr_code:'<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect width="180" height="180" fill="white"/><text x="10" y="90" fill="black">TEST QR</text></svg>'}});
 if(p.endsWith('/challenge'))return json(r,{id:'challenge-1'});
 if(p.endsWith('/verify')){if(body.code!==totp()){wrongMfa++;return json(r,{detail:'Invalid code'},422)}stage='aal2';enrolled=true;return json(r,{access_token:'aal2',refresh_token:'refresh2',expires_in:3600})}
 if(p==='/api/v1/auth/logout'){stage='none';return json(r,{})}
 if(p==='/api/v1/auth/refresh'){stage='aal2';return json(r,{access_token:'aal2',refresh_token:'refresh2',expires_in:3600})}
 if(p.startsWith('/storage/')){if(imageFailure)return json(r,{},404);const file=process.env.TEST_IMAGE_PATH||path.join(__dirname,'fixtures/evidence.png');return r.fulfill({status:200,contentType:'image/png',body:file?fs.readFileSync(file):Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j0S8AAAAASUVORK5CYII=','base64')})}
 if(stage!=='aal2')return json(r,{detail:'MFA required'},403);if(failNetwork)return json(r,{detail:'offline'},503);
 for(const e of events)if(expirySweep&&e.status==='pending'&&Date.parse(e.review_expires_at)<=Date.now()){e.status='timeout';e.version++}
 if(p==='/api/v1/me')return json(r,users[0]);
 if(p==='/api/v1/events'){const rows=u.searchParams.get('status')==='pending'?events.filter(e=>e.status==='pending'):events;return json(r,{items:rows})}
 if(p.endsWith('/decision')){const id=decodeURIComponent(p.split('/')[4]);const e=events.find(e=>e.event_id===id);if(!e||e.status!=='pending')return json(r,{detail:'Expired'},409);e.status=body.decision;e.version++;e.decision=body.decision;e.decision_time=iso(Date.now());return json(r,{event:e})}
 if(p.startsWith('/api/v1/events/')&&p.endsWith('/image'))return json(r,{signed_url:'https://unit.supabase.co/storage/v1/signed/test.png',expires_in:60});
 if(p.startsWith('/api/v1/events/'))return json(r,events.find(e=>e.event_id===decodeURIComponent(p.split('/')[4]))||{},events.some(e=>e.event_id===decodeURIComponent(p.split('/')[4]))?200:404);
 if(p==='/api/v1/telemetry')return json(r,{items:[telemetry()]});
 if(p.endsWith('/history'))return json(r,{items:[0,1,2,3,4].map(i=>({snapshot:{...telemetry(),latitude:17.123+i*.0001,longitude:42.456+i*.0001,updated_at:iso(Date.now()-i*3000)}}))});
 if(p==='/api/v1/summary'){const counts={};for(const k of ['pending','accepted','rejected','timeout'])counts[k]=events.filter(e=>e.status===k).length;return json(r,{server_time:iso(Date.now()),counts})}
 if(p==='/api/v1/archive'){let rows=events;const st=u.searchParams.get('status');if(st)rows=rows.filter(e=>e.status===st);const id=u.searchParams.get('event_id');if(id)rows=rows.filter(e=>e.event_id===id);return json(r,{items:rows,total:rows.length})}
 if(p==='/api/v1/admin/users'){if(req.method()==='POST'){users.push({id:'new-id',display_name:body.display_name,role:body.role,active:true});return json(r,{user:users.at(-1)},201)}return json(r,{items:users})}
 if(p==='/api/v1/admin/audit')return json(r,{items:[]});
 if(p==='/api/v1/capabilities')return json(r,{commands:[{code:'resume_patrol',label:'متابعة الدورية',enabled:true},{code:'return_to_launch',label:'العودة إلى نقطة الإقلاع',enabled:false}]});
 if(p==='/api/v1/commands')return json(r,{items:[]});
 return json(r,{detail:'Unmocked route '+p},404);
});
async function check(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS',name)}
async function settle(){await page.waitForFunction(()=>!S.syncing);await page.waitForTimeout(100)}
async function nav(name){await page.locator('[data-nav="'+name+'"]').first().click();await page.waitForFunction(n=>route().name===n,name);await settle()}
async function login(){await page.locator('#login-id').fill('MAR-001');await page.locator('#login-password').fill('test-password-only');await page.locator('#login-submit').click();await page.locator('#mfa-form').waitFor({state:'visible'})}
async function verify(){await page.locator('#mfa-code').fill(totp());await page.locator('#mfa-submit').click();await page.locator('#workspace').waitFor({state:'visible'});await settle()}
async function screenshot(name){await page.evaluate(()=>{window.scrollTo(0,0);document.activeElement?.blur();document.querySelector('#toast').hidden=true;let b=document.createElement('div');b.id='qa-label';b.textContent='لقطة اختبار محلي · بيانات اختبار · الخدمات الخارجية غير مرتبطة';b.style.cssText='position:absolute;top:0;left:0;right:0;text-align:center;background:#453923;color:#ffde9b;padding:8px;z-index:9999;font:12px Tahoma';document.body.append(b)});await page.screenshot({path:path.join(root,'previews',name),fullPage:true});await page.locator('#qa-label').evaluate(e=>e.remove())}
await page.goto('http://127.0.0.1:8770/unconfigured');
await check('Unconfigured production page has no dashboard/demo/account bypass',async()=>{assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(await page.locator('#configuration-note').isVisible(),true);assert.equal(await page.locator('#login-submit').isDisabled(),true);await page.evaluate(()=>location.hash='#/admin');assert.equal(await page.locator('#workspace').isVisible(),false)});
await screenshot('Login.png');await page.goto('http://127.0.0.1:8770/');
await check('Wrong password keeps the workspace locked',async()=>{await page.locator('#login-id').fill('MAR-001');await page.locator('#login-password').fill('wrong');await page.locator('#login-submit').click();await page.waitForFunction(()=>document.querySelector('#auth-error').textContent.length>0);assert.equal(await page.locator('#workspace').isVisible(),false)});
await login();await check('First login requires authenticator enrollment without operational requests',async()=>{assert.equal(await page.locator('#enroll-panel').isVisible(),true);assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(calls.filter(x=>x.p==='/api/v1/events').length,0)});
await check('Invalid authenticator code is rejected and dashboard stays locked',async()=>{await page.locator('#mfa-code').fill('000000');await page.locator('#mfa-submit').click();await page.waitForFunction(()=>document.querySelector('#auth-error').textContent.length>0);assert.equal(wrongMfa,1);assert.equal(await page.locator('#workspace').isVisible(),false)});
add('EVT-TEST-002');await verify();
await check('Verified ID + TOTP enters admin dashboard and removes enrollment secret',async()=>{assert.equal(await page.locator('#workspace').isVisible(),true);assert.equal(await page.locator('#mfa-secret').textContent(),'');assert.equal(await page.locator('#admin-nav').isVisible(),true);assert.equal(await page.locator('#filters').count(),0);assert.equal(await page.locator('#view table').count(),0)});
await check('Target marker and drone marker use independent coordinates',async()=>{const xy=await page.evaluate(()=>({d:S.drone.latitude,e:selectedEvent().latitude,layers:mapState.layers.getLayers().length}));assert.notEqual(xy.d,xy.e);assert.ok(xy.layers>=3);assert.equal(calls.some(x=>x.p.endsWith('.png')&&!x.p.startsWith('/storage/')),false)});
await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-image] img')).some(i=>i.complete&&i.naturalWidth>0));await screenshot('Dashboard.png');
await check('Accept saves status and does not turn suspect detection into confirmed identity',async()=>{await page.locator('[data-decision="accepted"]').first().click();await page.waitForFunction(()=>selectedEvent()?.status==='accepted');assert.equal(events[0].status,'accepted');await nav('events');await page.locator('[data-open="EVT-SUSPECT"]').click();await settle();assert.match(await page.locator('#view').innerText(),/مشتبه/);assert.match(await page.locator('#view').innerText(),/ليس لغمًا مؤكدًا/)});
await check('Event details show original JSON, target accuracy and drone snapshot',async()=>{assert.match(await page.locator('#view').innerText(),/دقة الهدف/);assert.match(await page.locator('#view').innerText(),/موقع الدرون وقت الرصد/);await page.locator('#view summary').click();assert.match(await page.locator('pre').innerText(),/image_projection/)});
await nav('archive');await check('Archive is a separate route with search and filter controls',async()=>{assert.equal(await page.locator('#filters').count(),1);assert.equal(await page.locator('#map').count(),0);await page.locator('#filter-status').selectOption('accepted');await page.locator('#filters button').click();await settle();assert.equal(await page.locator('tbody tr').count(),1)});
await screenshot('Archive.png');await nav('tracking');await check('Tracking has GPS fields and geographic map, zero coordinate is valid',async()=>{assert.match(await page.locator('#view').innerText(),/أقمار GPS/);assert.equal(await page.evaluate(()=>hasCoords({latitude:0,longitude:0})),true);assert.equal(await page.evaluate(()=>targetCoords({latitude:0,longitude:0,location_validity:'Unavailable'})),false);assert.equal(await page.evaluate(()=>droneCoords({latitude:17,longitude:42,gps_fix_type:'no_fix'})),false)});
await screenshot('Tracking.png');
await check('Geographic distance is labelled and computes reasonable metres',async()=>{const value=await page.evaluate(()=>haversine({latitude:0,longitude:0},{latitude:0,longitude:1}));assert.ok(value>111000&&value<111300)});
stale=true;await nav('commands');await check('Stale telemetry disables command requests',async()=>{assert.equal(await page.locator('[data-command="resume_patrol"]').isDisabled(),true)});stale=false;
await nav('admin');await check('New user flow provisions admin with a login ID',async()=>{await page.locator('#new-account').click();await page.locator('#account-name').fill('مدير اختبار');await page.locator('#account-id').fill('MAR-002');await page.locator('#account-email').fill('test@example.com');await page.locator('#account-password').fill('test-password-for-fixture');await page.locator('#account-send').click();await page.locator('#account-dialog').waitFor({state:'hidden'});await settle();assert.equal(users.at(-1).role,'admin');assert.equal(await page.locator('#account-password').inputValue(),'')});
expirySweep=false;const exp=add('EVT-EXPIRE');exp.review_expires_at=iso(Date.now()+1700);await page.evaluate(()=>S.selected='EVT-EXPIRE');await nav('dashboard');await check('Expired review disables decisions without browser inventing a final status',async()=>{await page.waitForTimeout(1800);assert.equal(await page.locator('[data-decision="accepted"]').first().isDisabled(),true);assert.equal(await page.evaluate(()=>selectedEvent().status),'pending');expirySweep=true;await page.evaluate(()=>sync());await settle();assert.equal(exp.status,'timeout')});
const rej=add('EVT-REJECT');await page.evaluate(()=>{S.selected='EVT-REJECT';return sync()});await check('Reject persists rejected state',async()=>{await page.locator('[data-decision="rejected"]').first().click();await page.waitForFunction(()=>selectedEvent()?.status==='rejected');assert.equal(rej.status,'rejected')});
add('EVT-OFFLINE');await page.evaluate(()=>{S.selected='EVT-OFFLINE';return sync()});failNetwork=true;await check('Service failure freezes decisions and shows connection warning',async()=>{await page.evaluate(()=>sync());assert.equal(await page.locator('#connection-error').isVisible(),true);assert.equal(await page.locator('[data-decision="accepted"]').isDisabled(),true)});failNetwork=false;await page.evaluate(()=>sync());
await check('Payload text is escaped rather than executed',async()=>{events[0].object='<img src=x onerror="window.pwned=1">';await page.evaluate(()=>sync());assert.equal(await page.evaluate(()=>window.pwned),undefined);assert.match(await page.locator('#view').innerText(),/<img/)});
await page.setViewportSize({width:390,height:844});await check('Mobile layout has no document overflow',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true));
events[0].object='boat';await page.evaluate(()=>sync());await page.evaluate(()=>document.activeElement?.blur());await screenshot('Mobile.png');await page.setViewportSize({width:320,height:844});await check('320px layout keeps the page inside viewport',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true));
await check('Logout clears tokens, secret and private UI; hash cannot restore session',async()=>{await page.evaluate(()=>{void sync()});await page.locator('#logout').click();await page.waitForTimeout(350);await page.locator('#auth-screen').waitFor({state:'visible'});await page.evaluate(()=>location.hash='#/archive');assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(await page.evaluate(()=>S.session),null);assert.equal(await page.evaluate(()=>S.pending.length+S.recent.length+S.history.length),0);assert.equal(await page.locator('#view').textContent(),'');assert.equal(await page.evaluate(()=>localStorage.length),0)});
await login();await check('Subsequent login challenges existing factor without reenrollment',async()=>assert.equal(await page.locator('#enroll-panel').isVisible(),false));await verify();await page.reload();await check('Page refresh does not restore a cached authenticated session',async()=>assert.equal(await page.locator('#workspace').isVisible(),false));
await check('No browser requests to Supabase Auth or database',async()=>assert.equal(calls.some(c=>c.p.startsWith('/auth/v1/')||c.p.startsWith('/rest/v1/')||c.hasApiKey),false));
await check('No uncaught browser errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(process.env.RESULTS_PATH||path.join(root,'tests/browser-results.json'),JSON.stringify(results,null,2));await browser.close();server.close();console.log(results.length+' checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
