/* Real PostgreSQL engine in PGlite, with minimal Supabase Auth/Storage fixtures.
   Tests SQL/RLS semantics locally; not hosted Supabase configuration or concurrency load. */
const fs=require('fs'),assert=require('assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const result=[];
(async()=>{const db=new PGlite();const sql=fs.readFileSync(require('path').join(__dirname,'../supabase/001_workspace.sql'),'utf8');
const admin='11111111-1111-1111-1111-111111111111', op='22222222-2222-2222-2222-222222222222', other='33333333-3333-3333-3333-333333333333';
async function check(name,fn){await fn();result.push({name,status:'PASS'});console.log('PASS',name);}
async function rpc(name,values,casts){return (await db.query(`select public.${name}(${values.map((_,i)=>'$'+(i+1)+(casts?.[i]?'::'+casts[i]:'')).join(',')}) as result`,values)).rows[0].result;}
async function role(name,id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+name);}
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,service_role;grant execute on function auth.uid() to authenticated,service_role;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select on storage.objects to authenticated;`);
await check('Migration executes atomically on PostgreSQL engine',()=>db.exec(sql));
await check('Independent-server migration executes on PostgreSQL',()=>db.exec(fs.readFileSync(require('path').join(__dirname,'../supabase/002_complete_server.sql'),'utf8')));
await db.query('insert into auth.users values ($1),($2),($3)',[admin,op,other]);
await db.query("insert into public.profiles(id,display_name,role) values($1,'Admin','admin'),($2,'Operator','operator'),($3,'Other','operator')",[admin,op,other]);
await db.exec("insert into public.missions(mission_id) values('M');insert into public.tracks(mission_id,track_id,object) values('M',1,'boat')");
async function event(id){await db.query("insert into public.events(event_id,mission_id,track_id,object,confidence,timestamp,image_path) values($1,'M',1,'boat',.9,now(),$2)",[id,`M/${id}.jpg`]);}
await event('E1');
await check('New event starts pending with server-owned 20-second deadline',async()=>{const e=(await db.query("select status,extract(epoch from review_expires_at-review_started_at) as seconds from public.events where event_id='E1'")).rows[0];assert.equal(e.status,'pending');assert.equal(Number(e.seconds),20);});
await role('authenticated',op);
await check('Operator can read authorized events',async()=>assert.equal((await db.query('select * from public.events')).rows.length,1));
await check('Operator cannot update event directly',async()=>{await assert.rejects(db.exec("update public.events set status='accepted'"),/permission denied/);});
await check('Operator cannot promote own role',async()=>{await assert.rejects(db.exec("update public.profiles set role='admin'"),/permission denied/);});
await check('Operator cannot call service-only decision RPC',async()=>{await assert.rejects(rpc('review_event',['E1',op,'accepted',0]),/permission denied/);});
await check('Operator cannot read other profile or audit',async()=>{assert.equal((await db.query('select * from public.profiles')).rows.length,1);assert.equal((await db.query('select * from public.audit_log')).rows.length,0);});
await role('anon');await check('Anonymous cannot read events',async()=>{await assert.rejects(db.exec('select * from public.events'),/permission denied/);});
await role('service_role');
await check('Review records accepted with verified actor and timestamp',async()=>{const r=await rpc('review_event',['E1',op,'accepted',0]);assert.equal(r.code,200);assert.equal(r.event.status,'accepted');assert.equal(r.event.operator_id,op);assert.ok(r.event.decision_time);});
await check('Same actor same decision is idempotent; different decision conflicts',async()=>{assert.equal((await rpc('review_event',['E1',op,'accepted',0])).code,200);assert.equal((await rpc('review_event',['E1',op,'rejected',0])).code,409);assert.equal((await rpc('review_event',['E1',other,'accepted',0])).code,409);});
await check('Final-state protection applies even to accidental direct backend UPDATE',async()=>{await assert.rejects(db.exec("update public.events set status='timeout',decision='timeout',operator_id=null where event_id='E1'"),/immutable/);});
await db.exec('reset role');await event('E2');await role('service_role');
await check('Stale version fails without finalizing pending record',async()=>{assert.equal((await rpc('review_event',['E2',op,'accepted',12])).code,409);assert.equal((await db.query("select status from public.events where event_id='E2'")).rows[0].status,'pending');});
await check('Early timeout is rejected',async()=>{await assert.rejects(db.exec("update public.events set status='timeout',decision='timeout',decision_time=now(),operator_id=null where event_id='E2'"),/before deadline/);});
// Fixture only: move deadline into the past under owner while trigger disabled.
await db.exec("reset role;alter table public.events disable trigger protect_event_state;update public.events set review_started_at=now()-interval '30 seconds',review_expires_at=now()-interval '10 seconds' where event_id='E2';alter table public.events enable trigger protect_event_state;set role service_role");
await check('Expired manual decision produces persisted timeout and conflict',async()=>{const r=await rpc('review_event',['E2',op,'accepted',0]);assert.equal(r.code,409);assert.equal(r.event.status,'timeout');});
await db.exec('reset role');await event('E3');await db.exec("alter table public.events disable trigger protect_event_state;update public.events set review_started_at=now()-interval '30 seconds',review_expires_at=now()-interval '10 seconds' where event_id='E3';alter table public.events enable trigger protect_event_state;set role service_role");
await check('Background sweep expires due events once without any browser',async()=>{assert.equal(await rpc('expire_pending_events',[]),1);assert.equal(await rpc('expire_pending_events',[]),0);});
await check('Audit records one final decision per event',async()=>assert.equal((await db.query('select count(*) as n from public.audit_log')).rows[0].n,3));
await db.exec("reset role;insert into storage.objects(bucket_id,name) values('event-images','M/E1.jpg'),('event-images','unlinked.jpg')");await role('authenticated',op);
await check('Storage RLS exposes linked images only',async()=>{const r=(await db.query('select name from storage.objects')).rows;assert.deepEqual(r.map(x=>x.name),['M/E1.jpg']);});
await role('service_role');
await check('Only admin can change membership; self-disable is blocked',async()=>{assert.equal((await rpc('set_member_access',[op,other,false])).code,403);assert.equal((await rpc('set_member_access',[admin,admin,false])).code,400);assert.equal((await rpc('set_member_access',[admin,other,false])).code,200);});
await role('authenticated',other);
await check('Disabled user loses event and image reads',async()=>{assert.equal((await db.query('select * from public.events')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);});
await role('service_role');
await db.exec("insert into public.command_capabilities(code,label,enabled) values('hold','Hold',true);insert into public.drone_state(drone_id,mission_id,updated_at) values('UAV','M',now())");
let stamp=(await db.query("select updated_at::text as t from public.drone_state where drone_id='UAV'")).rows[0].t;const key='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';const values=[op,key,'hold','UAV','M',stamp,'Test command'];
await check('Command records queued; identical retry returns same request',async()=>{const a=await rpc('request_command',values),b=await rpc('request_command',values);assert.equal(a.code,202);assert.equal(a.command.status,'queued');assert.equal(b.code,200);assert.equal(a.command.command_id,b.command.command_id);});
await check('Same request key with altered body conflicts',async()=>assert.equal((await rpc('request_command',[...values.slice(0,6),'Changed'])).code,409));
await check('Unlisted command is denied',async()=>assert.equal((await rpc('request_command',[op,'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','unknown','UAV','M',stamp,'Test'])).code,403));
await db.exec("update public.drone_state set updated_at=now()-interval '60 seconds'");
await check('Stale telemetry prevents command request',async()=>assert.equal((await rpc('request_command',[op,'cccccccc-cccc-cccc-cccc-cccccccccccc','hold','UAV','M',stamp,'Test'])).code,409));
await db.exec('reset role;set role service_role');
const incoming={event_id:'INGEST-1',mission_id:'NEW-M',track_id:10,object:'floating_mine_candidate',person_visible:null,confidence:.7,latitude:null,longitude:null,location_validity:'Unavailable',timestamp:new Date().toISOString(),image_path:'events/test/image.jpg',bbox:[.1,.2,.5,.6]};
await check('Event ingestion creates mission/track/event and preserves uncertain classification',async()=>{const r=await rpc('ingest_event',[JSON.stringify(incoming),'same-fingerprint']);assert.equal(r.code,201);assert.equal(r.event.object,'floating_mine_candidate');assert.equal(r.event.person_visible,null);});
await check('Identical ingest retry preserves review deadline; changed duplicate is rejected',async()=>{const a=await rpc('ingest_event',[JSON.stringify(incoming),'same-fingerprint']);const b=await rpc('ingest_event',[JSON.stringify(incoming),'same-fingerprint']);assert.equal(a.code,200);assert.equal(a.event.review_started_at,b.event.review_started_at);assert.equal((await rpc('ingest_event',[JSON.stringify(incoming),'changed'])).code,409);});
await check('Telemetry rejects older sample instead of overwriting current state',async()=>{const now=new Date().toISOString();const payload={drone_id:'T-UAV',mission_id:'NEW-M',updated_at:now,battery_percent:70};assert.equal((await rpc('upsert_telemetry',[JSON.stringify(payload)])).code,200);payload.updated_at='2020-01-01T00:00:00Z';assert.equal((await rpc('upsert_telemetry',[JSON.stringify(payload)])).code,409);});
await check('WebSocket ticket can be consumed once only',async()=>{await db.query("insert into public.ws_tickets(ticket_hash,user_id,expires_at) values('hash',$1,now()+interval '30 seconds')",[op]);assert.equal(await rpc('consume_ws_ticket',['hash']),op);assert.equal(await rpc('consume_ws_ticket',['hash']),null);});
await check('Expired WebSocket ticket is denied',async()=>{await db.query("insert into public.ws_tickets(ticket_hash,user_id,expires_at) values('expired',$1,now()-interval '1 second')",[op]);assert.equal(await rpc('consume_ws_ticket',['expired']),null);});
await check('Role promotion requires administrator; self role changes are denied',async()=>{assert.equal((await rpc('set_member_role',[op,other,'admin'])).code,403);assert.equal((await rpc('set_member_role',[admin,admin,'operator'])).code,400);assert.equal((await rpc('set_member_role',[admin,op,'admin'])).code,200);});
await check('Command claiming is one-time and acknowledgement follows ordered transitions',async()=>{await db.exec("update public.drone_state set updated_at=now() where drone_id='UAV'");const claimed=await db.query("select * from public.claim_commands('UAV',10)");assert.equal(claimed.rows.length,1);const id=claimed.rows[0].command_id;assert.equal((await db.query("select * from public.claim_commands('UAV',10)")).rows.length,0);assert.equal((await rpc('acknowledge_command',[id,'acknowledged','Too early'])).code,409);assert.equal((await rpc('acknowledge_command',[id,'sent','Sent to external system'])).code,200);assert.equal((await rpc('acknowledge_command',[id,'acknowledged','External acknowledgement'])).code,200);assert.equal((await rpc('acknowledge_command',[id,'failed','Late overwrite'])).code,409);});

await db.exec('reset role');
await db.exec(`create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('aal',current_setting('request.jwt.claim.aal',true)) $$;grant execute on function auth.jwt() to authenticated,service_role;`);
await check('Live migration installs ID, AAL2 policies and telemetry extensions',()=>db.exec(fs.readFileSync(require('path').join(__dirname,'../supabase/003_live_workspace.sql'),'utf8')));
await check('Advisor hardening moves helpers and preserves policy dependencies',async()=>{await db.exec(fs.readFileSync(require('path').join(__dirname,'../supabase/migrations/20260929173243_maritime_advisor_hardening.sql'),'utf8'));const r=(await db.query("select to_regprocedure('public.has_workspace_access()') as exposed, has_function_privilege('anon','maritime_private.has_workspace_access()','execute') as anon_execute, has_function_privilege('authenticated','maritime_private.has_workspace_access()','execute') as member_execute")).rows[0];assert.equal(r.exposed,null);assert.equal(r.anon_execute,false);assert.equal(r.member_execute,true);});
await role('authenticated',admin);
await db.exec("select set_config('request.jwt.claim.aal','aal1',false)");
await check('Password-only admin cannot read any events/profiles/images/history',async()=>{for(const table of ['public.events','public.profiles','storage.objects','public.telemetry_history'])assert.equal((await db.query('select * from '+table)).rows.length,0);});
await check('AAL1 can inspect only its authenticated session assurance',async()=>{const security=await rpc('current_session_security',[]);assert.equal(security.aal,'aal1');assert.equal(security.user_id,admin);});
await check('Login ID mapping and rate data cannot be read by authenticated users',async()=>{for(const table of ['public.login_identities','public.login_attempts'])await assert.rejects(db.query('select * from '+table),/permission denied/);});
await db.exec("select set_config('request.jwt.claim.aal','aal2',false)");
await check('Verified AAL2 admin can read authorized records',async()=>assert.ok((await db.query('select * from public.events')).rows.length>0));
await role('authenticated',other);
await check('Disabled AAL2 account still cannot read data',async()=>assert.equal((await db.query('select * from public.events')).rows.length,0));
await role('service_role');
await check('Persistent login limiter denies excess attempts',async()=>{assert.equal(await rpc('consume_login_attempt',['key',2,60]),true);assert.equal(await rpc('consume_login_attempt',['key',2,60]),true);assert.equal(await rpc('consume_login_attempt',['key',2,60]),false);});
await check('Expanded telemetry stores history and preserves missing values',async()=>{let state={drone_id:'GPS-UAV',mission_id:'M',latitude:17.12,longitude:42.45,updated_at:new Date().toISOString(),distance_travelled_m:321,heading_deg:0,gps_fix_type:'3d',gps_satellites:14};let r=await rpc('upsert_telemetry',[JSON.stringify(state)]);assert.equal(r.code,200);assert.equal(r.state.heading_deg,0);assert.equal(r.state.battery_percent,null);assert.equal(r.state.distance_travelled_m,321);let h=(await db.query("select * from public.telemetry_history where drone_id='GPS-UAV'")).rows;assert.equal(h.length,1);assert.equal(h[0].snapshot.gps_satellites,14);assert.equal((await rpc('upsert_telemetry',[JSON.stringify(state)])).code,409);});
await check('Target coordinates and drone GPS snapshot remain independent',async()=>{const input={...incoming,event_id:'GPS-EVENT',latitude:17.11,longitude:42.43,location_validity:'Approximate',drone_latitude:17.12,drone_longitude:42.45,drone_id:'GPS-UAV',target_accuracy_m:25,location_source:'image_projection'};const result=await rpc('ingest_event',[JSON.stringify(input),'gps-fingerprint']);assert.equal(result.code,201);assert.equal(result.event.latitude,17.11);assert.equal(result.event.drone_latitude,17.12);assert.equal(result.event.target_accuracy_m,25);assert.equal(result.event.location_source,'image_projection');});
await check('Old internal telemetry function is not exposed to service role',async()=>await assert.rejects(rpc('upsert_telemetry_v2',[JSON.stringify({})]),/permission denied/));
await check('Case-normalized unique login ID is enforced',async()=>{await db.query('insert into public.login_identities values ($1,$2,$3)',['mar-001',admin,'admin@example.com']);await assert.rejects(db.query('insert into public.login_identities values ($1,$2,$3)',['MAR-002',other,'other@example.com']),/check constraint/);});
await db.close();fs.writeFileSync(process.env.RESULTS_PATH||'/tmp/maritime-db-results.json',JSON.stringify(result,null,2));console.log(`${result.length} checks passed`);
})().catch(e=>{console.error(e);process.exit(1)});
