'use strict';
/* API URL and display settings only. No Supabase keys belong in the browser.
   Build with: python build_frontend.py. No demo mode and no embedded accounts. */
const CONFIG = Object.freeze({
  mode: 'live',
  phase2ApiUrl: '', // HTTPS URL of this package's server/app.py, without /api/v1
  pollIntervalMs: 5000,
  requestTimeoutMs: 15000,
  telemetryFreshMs: 15000,
  websocketEnabled: true,
  mapTileUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
  mapAttribution: '© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>',
  allowLocalApi: false // true ONLY for HTTP localhost development; never a remote HTTP server
});
const API_BASE=(CONFIG.phase2ApiUrl||location.origin).replace(/\/$/,'');
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={boat:'قارب',swimmer:'رصد سباح',buoy:'عوامة',floating_mine_candidate:'جسم مشتبه بأنه لغم عائم','person_in_water?':'شخص محتمل في الماء'};
const statuses={pending:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض',timeout:'انتهت المهلة'};
const validity={Valid:'موقع صالح حسب المصدر',Approximate:'موقع تقريبي',Unavailable:'الموقع غير متاح'};
const sources={unknown:'لم يُحدد المصدر',target_gps:'GPS مستقل على الهدف',image_projection:'تقدير بإسقاط الصورة',manual:'إدخال يدوي'};
const S={session:null,profile:null,factor:null,enrollment:null,generation:0,refreshing:null,syncing:null,pending:[],recent:[],history:[],historyTotal:0,detail:null,counts:{},drone:null,drones:[],track:[],commands:[],commandLog:[],users:[],audit:[],selected:null,droneId:null,page:0,filters:{id:'',status:'',object:'',from:'',to:''},lastSync:0,error:'',clockOffset:0,ws:null,wsRetry:null,media:new Map(),busy:new Set(),command:null,commandKey:null,commandPayload:null};
const controllers=new Set();let routeVersion=0,mapState=null,toastTimer;
function configuration(){
 if(CONFIG.mode!=='live')throw Error('هذه النسخة مخصصة للتشغيل الفعلي.');
 for(const [name,value] of [['api',API_BASE]]){
  let u;try{u=new URL(value)}catch{throw Error('أكمل إعداد روابط الخدمات في CONFIG.')}
  const local=name==='api'&&CONFIG.allowLocalApi&&u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname);
  if((u.protocol!=='https:'&&!local)||u.username||u.password||u.search||u.hash)throw Error('تتطلب خدمات التشغيل روابط HTTPS صالحة.');
 }
}
let configured=true;try{configuration()}catch{configured=false;$('#configuration-note').hidden=false;$('#login-submit').disabled=true}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000)}
function failure(error){if(error.status===401)return 'المعرّف أو كلمة المرور غير صحيحة، أو انتهت الجلسة.';if(error.status===429)return 'محاولات كثيرة. انتظر عدة دقائق قبل المحاولة مجددًا.';if(error.status===403)return 'العملية غير مسموحة. تحقق من صلاحية الحساب وإكمال Authenticator.';if(error.status===409)return 'تغيرت البيانات أو انتهت المهلة. حُدّثت الصفحة؛ راجع الحالة قبل المحاولة.';if(error.status===400||error.status===422)return 'تعذر قبول البيانات. راجع الحقول أو رمز المصادقة ثم أعد المحاولة.';return error.message||'تعذر إكمال العملية.'}
async function request(url,options={}){const generation=S.generation;const controller=new AbortController();controllers.add(controller);const t=setTimeout(()=>controller.abort(),CONFIG.requestTimeoutMs);try{const r=await fetch(url,{...options,signal:controller.signal,cache:'no-store',referrerPolicy:'no-referrer'});let data;try{data=await r.json()}catch{throw Error('استجابة غير صالحة من الخدمة.')}if(generation!==S.generation)throw Error('أُغلقت الجلسة.');if(!r.ok){const e=Error(r.status>=500?'خدمة البيانات غير متاحة حاليًا. حاول لاحقًا.':'تعذر إكمال الطلب.');e.status=r.status;throw e}return {data,response:r};}catch(e){if(e.name==='AbortError')throw Error('انتهت مهلة الاتصال. تحقق من الحالة قبل إعادة الإرسال.');throw e}finally{clearTimeout(t);controllers.delete(controller)}}
function authRequest(path,body,method='POST'){return request(API_BASE+'/api/v1/auth/'+path,{method,headers:{'Content-Type':'application/json',...(S.session?{Authorization:'Bearer '+S.session.access_token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})})}
function saveSession(data){if(!data?.access_token||!data?.refresh_token)throw Error('لم تُستلم جلسة صالحة.');S.session={access_token:data.access_token,refresh_token:data.refresh_token,expires_at:Date.now()+Number(data.expires_in||3600)*1000}}
async function token(){if(!S.session)throw Error('تسجيل الدخول مطلوب.');if(S.session.expires_at-Date.now()<60000){if(!S.refreshing){const gen=S.generation;S.refreshing=authRequest('refresh',{refresh_token:S.session.refresh_token}).then(({data})=>{if(gen!==S.generation)throw Error('أُغلقت الجلسة.');saveSession(data)}).catch(e=>{if(gen===S.generation)clearSession();throw e}).finally(()=>S.refreshing=null)}await S.refreshing}if(!S.session)throw Error('انتهت الجلسة.');return S.session.access_token}
async function api(path,options={}){const t=await token();return request(API_BASE+'/api/v1'+path,{...options,headers:{Authorization:'Bearer '+t,...(!(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...options.headers}})}

function clearMfa(){S.factor=null;S.enrollment=null;$('#mfa-qr').removeAttribute('src');$('#mfa-secret').textContent='';$('#mfa-code').value='';$('#enroll-panel').hidden=true;$('#mfa-form').hidden=true;$('#login-form').hidden=false;$('#auth-title').textContent='مرحبًا بعودتك';$('#auth-description').textContent='سجّل الدخول بمعرّف حسابك، ثم أكمل التحقق عبر تطبيق Authenticator.'}
function closeSocket(){clearTimeout(S.wsRetry);S.wsRetry=null;if(S.ws){S.ws.onclose=null;S.ws.close();S.ws=null}}
function clearSession(){S.generation++;for(const c of controllers)c.abort();closeSocket();S.session=null;S.profile=null;S.lastSync=0;S.error='';S.pending=[];S.recent=[];S.history=[];S.historyTotal=0;S.counts={};S.page=0;S.droneId=null;S.busy.clear();S.detail=null;S.drone=null;S.drones=[];S.track=[];S.users=[];S.audit=[];S.commandLog=[];S.commands=[];S.media.clear();S.selected=null;S.command=null;S.commandPayload=null;S.commandKey=null;S.syncing=null;for(const d of $$('dialog'))d.close();$('#account-password').value='';$('#login-password').value='';clearMfa();destroyMap();$('#view').innerHTML='';$('#workspace').hidden=true;$('#auth-screen').hidden=false;$('#auth-error').textContent='';$('#profile-name').textContent='';}
async function logout(){const session=S.session;clearSession();if(session){try{await request(API_BASE+'/api/v1/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+session.access_token}})}catch{toast('أُغلقت الجلسة محليًا؛ تعذر تأكيد إلغائها لدى الخدمة.')}}}
async function login(e){e.preventDefault();if(!configured)return;$('#login-submit').disabled=true;$('#auth-error').textContent='';try{const {data}=await request(API_BASE+'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login_id:$('#login-id').value.trim(),password:$('#login-password').value})});saveSession(data);await prepareMfa();}catch(error){clearSession();$('#auth-error').textContent=failure(error)}finally{$('#login-password').value='';$('#login-submit').disabled=!configured}}
async function prepareMfa(){
 const {data:user}=await authRequest('user',undefined,'GET');const factors=(user.factors||[]).filter(f=>f.factor_type==='totp');const verified=factors.find(f=>f.status==='verified');
 $('#login-form').hidden=true;$('#mfa-form').hidden=false;$('#auth-title').textContent=verified?'التحقق من هويتك':'إعداد Authenticator';$('#auth-description').textContent=verified?'افتح تطبيق المصادقة وأدخل الرمز الحالي المكوّن من 6 أرقام.':'اربط تطبيق المصادقة بحسابك مرة واحدة لإكمال الدخول الآمن.';
 if(verified){S.factor=verified.id}else{
  // Unverified enrollments cannot authorize access; remove only incomplete setup leftovers.
  for(const f of factors.filter(f=>f.status==='unverified'))await authRequest('factors/'+encodeURIComponent(f.id),undefined,'DELETE');
  const {data}=await authRequest('factors',{factor_type:'totp',friendly_name:'Maritime Authenticator',issuer:'Maritime Operations'});S.factor=data.id;S.enrollment=data.id;
  const qr=data.totp?.qr_code||'';if(qr.startsWith('<svg'))$('#mfa-qr').src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qr);else if(qr.startsWith('data:image/svg+xml'))$('#mfa-qr').src=qr;else throw Error('تعذر عرض رمز إعداد المصادقة.');
  $('#mfa-secret').textContent=data.totp.secret;$('#enroll-panel').hidden=false;
 }
 $('#mfa-code').focus();
}
async function verifyMfa(e){e.preventDefault();$('#mfa-submit').disabled=true;$('#auth-error').textContent='';const gen=S.generation;try{const factor=encodeURIComponent(S.factor);const {data:challenge}=await authRequest('factors/'+factor+'/challenge',{});const {data}=await authRequest('factors/'+factor+'/verify',{challenge_id:challenge.id,code:$('#mfa-code').value.trim()});if(gen!==S.generation)return;saveSession(data);const {data:profile}=await api('/me');if(gen!==S.generation)return;S.profile=profile;clearMfa();$('#auth-screen').hidden=true;$('#workspace').hidden=false;$('#profile-name').textContent=profile.display_name;$('#profile-role').textContent=profile.role==='admin'?'مدير العمليات':'مشغّل';$('#avatar').textContent=(profile.display_name||'م').slice(0,1);$('#admin-nav').hidden=profile.role!=='admin';await navigate();void connectSocket();}catch(error){if(gen===S.generation){$('#auth-error').textContent=failure(error);$('#mfa-code').value='';$('#mfa-code').focus();}}finally{$('#mfa-submit').disabled=false}}
function route(){const raw=location.hash.slice(2).split('/');let id='';try{id=decodeURIComponent(raw.slice(1).join('/'))}catch{}return {name:['dashboard','tracking','events','archive','commands','admin','event'].includes(raw[0])?raw[0]:'dashboard',id}}
async function navigate(){routeVersion++;if(!S.profile)return;destroyMap();render();await sync();$('#content').focus({preventScroll:true})}
function nav(name){location.hash='#/'+name}
function now(){return Date.now()+S.clockOffset}
function freshness(){const t=Date.parse(S.drone?.updated_at);return !!S.drone&&Number.isFinite(t)&&now()-t>=-5000&&now()-t<CONFIG.telemetryFreshMs}
function canReview(e){const r=remaining(e);return e?.status==='pending'&&r!==null&&r>0&&!S.error&&Date.now()-S.lastSync<CONFIG.telemetryFreshMs&&!S.busy.has(e.event_id)}
function remaining(e){const t=Date.parse(e?.review_expires_at);return Number.isFinite(t)?Math.max(0,Math.ceil((t-now())/1000)):null}
const time=v=>v!=null&&Number.isFinite(typeof v==='number'?v:Date.parse(v))?new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'medium',calendar:'gregory',hour12:false}).format(new Date(v)):'غير متاح';
const number=(v,d=1)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
const label=o=>types[o]||o||'نوع غير معروف';
const uncertain=o=>o==='floating_mine_candidate'?'جسم مشتبه به · ليس لغمًا مؤكدًا':o==='person_in_water?'?'شخص محتمل في الماء · غير مؤكد':o==='swimmer'?'رصد سباح يحتاج تحققًا بشريًا':'';
function pill(s){return `<span class="pill ${esc(s)}">${esc(statuses[s]||s||'غير متاح')}</span>`}
function hasCoords(x){return typeof x?.latitude==='number'&&Number.isFinite(x.latitude)&&Math.abs(x.latitude)<=90&&typeof x.longitude==='number'&&Number.isFinite(x.longitude)&&Math.abs(x.longitude)<=180}
function targetCoords(e){return hasCoords(e)&&e.location_validity!=='Unavailable'}
function droneCoords(d){return hasCoords(d)&&d.gps_fix_type!=='no_fix'}
function coords(e){return hasCoords(e)?`${e.latitude.toFixed(6)}, ${e.longitude.toFixed(6)}`:'غير متاحة'}
function selectedEvent(){return [...S.pending,...S.recent,S.detail].filter(Boolean).find(e=>e.event_id===S.selected)||S.pending[0]||S.recent[0]||null}
async function sync(){if(!S.profile)return;if(S.syncing)return S.syncing;const gen=S.generation,rv=routeVersion,r=route();S.syncing=(async()=>{try{
 const results=await Promise.all([api('/me'),api('/events?status=pending&limit=100'),api('/events?limit=24'),api('/telemetry'),api('/summary')]);if(gen!==S.generation)return;
 S.profile=results[0].data;S.pending=results[1].data.items;S.recent=results[2].data.items;S.drones=results[3].data.items;S.drone=S.drones.find(d=>d.drone_id===S.droneId)||S.drones[0]||null;S.droneId=S.drone?.drone_id||null;S.counts=results[4].data.counts||{};const serverTime=Date.parse(results[4].data.server_time);if(Number.isFinite(serverTime))S.clockOffset=serverTime-Date.now();
 if(!S.selected)S.selected=S.pending[0]?.event_id||S.recent[0]?.event_id||null;
 if(S.drone&&(r.name==='tracking'||r.name==='dashboard')){const q=new URLSearchParams();if(S.drone.mission_id)q.set('mission_id',S.drone.mission_id);S.track=(await api('/telemetry/'+encodeURIComponent(S.drone.drone_id)+'/history?'+q)).data.items.map(x=>x.snapshot).filter(Boolean).reverse();}
 if(r.name==='archive'){const f=S.filters,q=new URLSearchParams({limit:'20',offset:String(S.page*20)});if(f.id)q.set('event_id',f.id);if(f.status)q.set('status',f.status);if(f.object)q.set('object',f.object);if(f.from)q.set('from_date',f.from);if(f.to)q.set('to_date',f.to);const {data}=await api('/archive?'+q);S.history=data.items;S.historyTotal=data.total;}
 if(r.name==='event'){S.detail=(await api('/events/'+encodeURIComponent(r.id))).data;}
 if(r.name==='commands'){const [caps,log]=await Promise.all([api('/capabilities'),api('/commands')]);S.commands=caps.data.commands;S.commandLog=log.data.items;}
 if(r.name==='admin'&&S.profile.role==='admin'){const [users,audit]=await Promise.all([api('/admin/users'),api('/admin/audit')]);S.users=users.data.items;S.audit=audit.data.items;}
 if(gen!==S.generation)return;S.error='';S.lastSync=Date.now();if(rv===routeVersion)render();
 }catch(e){if(gen!==S.generation)return;if(e.status===401||e.status===403){clearSession();$('#auth-error').textContent=failure(e);return}S.error=failure(e);if(rv===routeVersion)render();}finally{if(gen===S.generation){S.syncing=null;if(rv!==routeVersion)void sync();}}})();return S.syncing}
function heading(kicker,title,description,actions=''){return `<div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div><div class="actions">${actions}</div></div>`}
function metrics(){return `<div class="metrics">${[['pending','بانتظار القرار','نافذة مراجعة 20 ثانية'],['accepted','تم قبولها','قرار بشري مسجل'],['rejected','تم رفضها','محفوظة في الأرشيف'],['timeout','انتهت مهلتها','دون قرار في الوقت المحدد']].map(([k,n,d])=>`<div class="metric"><span>${n}</span><strong>${S.counts[k]??'—'}</strong><small>${d}</small></div>`).join('')}</div>`}
function media(e,small=false){return `<div class="media" ${e?.image_path?`data-image="${esc(e.event_id)}"`:''}>${!small?'<span class="media-tag">دليل الحدث الأصلي</span>':''}<div class="media-message"><span>◫</span>${e?.image_path?'تحميل الصورة…':'لم تُستلم صورة'}${!small?'<p>تُعرض الصورة المسجلة مع هذا الحدث عند توفرها.</p>':''}</div></div>`}
function review(e){if(!e)return '';if(e.status!=='pending')return `<div class="notice info">${pill(e.status)} ${e.decision_time?'سُجل القرار: '+esc(time(e.decision_time)):''} · القبول لا يؤكد هوية الجسم.</div>`;return `<div data-review="${esc(e.event_id)}"><div class="review-clock"><span>الوقت المتبقي لاتخاذ القرار</span><strong data-timer>—</strong></div><div class="progress"><i data-progress></i></div><div class="review-buttons"><button class="primary" data-decision="accepted" data-id="${esc(e.event_id)}">قبول</button><button class="danger" data-decision="rejected" data-id="${esc(e.event_id)}">رفض</button><button data-open="${esc(e.event_id)}">التفاصيل</button></div><small data-review-note></small></div>`}
function datum(title,value){return `<div class="datum"><small>${title}</small><strong>${value}</strong></div>`}
function focusCard(e){return `<section class="panel"><div class="panel-head"><div><h2>${e?esc(label(e.object)):'دليل الحدث'}</h2><small class="mono">${esc(e?.event_id||'بانتظار استقبال حدث')}</small></div>${e?pill(e.status):'<span class="pill">لا توجد أحداث</span>'}</div>${media(e)}<div class="panel-body">${e?`<div class="event-data">${datum('الثقة',number(e.confidence==null?null:e.confidence*100)+'%')}${datum('وقت الكشف',esc(time(e.timestamp)))}${datum('موقع الهدف',esc(validity[e.location_validity]||'غير متاح'))}${datum('إحداثيات الهدف',`<span class="mono">${targetCoords(e)?esc(coords(e)):'غير متاحة'}</span>`)}${datum('المهمة',esc(e.mission_id))}${datum('رقم التتبع',esc(e.track_id))}</div>${uncertain(e.object)?`<p class="uncertain">${uncertain(e.object)}</p>`:''}${review(e)}${e.status!=='pending'?`<button class="full" data-open="${esc(e.event_id)}">فتح تفاصيل الحدث</button>`:''}`:'<div class="empty">عند استقبال هدف، ستظهر هنا الصورة والبيانات وأزرار المراجعة.</div>'}</div></section>`}
function queue(){return `<section class="panel"><div class="panel-head"><div><h2>طابور المراجعة</h2><small>اختر حدثًا لعرض صورته واتخاذ القرار</small></div><span class="pill pending">${S.pending.length}</span></div><div class="queue">${S.pending.length?S.pending.map(e=>`<article class="queue-item ${selectedEvent()?.event_id===e.event_id?'selected':''}"><div class="queue-top">${media(e,true)}<div><h3>${esc(label(e.object))}</h3><small class="mono">${esc(e.event_id)}</small><small>الثقة ${number(e.confidence==null?null:e.confidence*100)}%</small></div></div>${uncertain(e.object)?`<p class="uncertain">${uncertain(e.object)}</p>`:''}<button data-select="${esc(e.event_id)}">عرض ومراجعة</button></article>`).join(''):'<div class="empty">لا توجد أحداث معلقة.<br>ستظهر الأحداث الجديدة فور وصولها.</div>'}</div>${S.pending.length>=100?'<div class="notice">عرض أول 100 حدث. راجع بقية الأحداث من الأرشيف.</div>':''}</section>`}
function haversine(a,b){if(!hasCoords(a)||!hasCoords(b))return null;const rad=v=>v*Math.PI/180;const x=Math.sin(rad(b.latitude-a.latitude)/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(rad(b.longitude-a.longitude)/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(x),Math.sqrt(Math.max(0,1-x)))}
function telemetry(){const d=S.drone||{};const home={latitude:d.home_latitude,longitude:d.home_longitude};const computed=d.distance_to_home_m==null&&droneCoords(d)?haversine(d,home):null;const cells=[['الشحن',d.battery_percent,'%',null],['السرعة الأرضية',d.speed_mps,'م/ث',d.speed_mps!=null?number(d.speed_mps*3.6)+' كم/س':null],['الارتفاع',d.altitude_m,'م','وفق مرجع المصدر'],['البعد عن نقطة العودة',d.distance_to_home_m??computed,'م',computed!==null?'مسافة أفقية محسوبة من GPS':null],['المسافة المقطوعة',d.distance_travelled_m,'م','من نظام الطائرة'],['زمن الرحلة',d.flight_time_s==null?null:d.flight_time_s/60,'دقيقة',null],['جهد البطارية',d.battery_voltage_v,'V',null],['جودة الاتصال',d.link_quality_percent,'%',null],['الاتجاه',d.heading_deg,'°',null],['أقمار GPS',d.gps_satellites,'',null],['دقة هندسة GPS',d.gps_hdop,'HDOP','ليست دقة بالمتر'],['السرعة الرأسية',d.vertical_speed_mps,'م/ث',null]];return `<section class="panel"><div class="panel-head"><div><h2>بيانات الدرون</h2><small>${d.drone_id?esc(d.drone_id):'لا توجد طائرة متصلة'}</small></div><span class="pill ${freshness()?'accepted':'pending'}">${!S.drone?'بانتظار البيانات':freshness()?'بيانات حديثة':'آخر بيانات · متقادمة'}</span></div><div class="telemetry-grid">${cells.map(([n,v,u,h])=>`<div class="telemetry-cell"><span>${n}</span><strong>${number(v)} <em>${v==null?'':u}</em></strong><small>${v==null?'غير مستلمة':h||'قيمة مستلمة'}</small></div>`).join('')}</div><div class="metadata"><span>وضع الطيران: ${esc(d.flight_mode||'غير متاح')}</span><span>المهمة: ${esc(d.mission_id||'غير متاحة')}</span><span>الحالة: ${esc(d.mission_state||'غير متاحة')}</span><span>المحركات: ${d.armed==null?'غير معروف':d.armed?'مسلّحة':'غير مسلّحة'}</span><span>GPS: ${esc(d.gps_fix_type||'لم يحدد المصدر')}</span><span>الشبكة: ${esc(d.connection_type||'غير متاحة')}</span><span>الإشارة: ${number(d.signal_dbm)} dBm</span><span>آخر تحديث: ${esc(time(d.updated_at))}</span></div></section>`}
function mapPanel(large=false){return `<section class="panel"><div class="panel-head"><div><h2>موقع الدرون والهدف</h2><small>علامتان منفصلتان · إحداثيات WGS84</small></div>${large?'':'<button data-nav="tracking">توسيع ↗</button>'}</div><div class="map-tools"><button id="map-center">توسيط المواقع</button><button id="map-basemap">تحميل خريطة الشوارع</button><small id="map-note">الإحداثيات تعمل دون تحميل خلفية خارجية.</small></div><div class="map-wrapper"><div id="map" class="map ${large?'large':''}" aria-label="خريطة موقع الدرون والهدف"></div><div id="map-empty" class="map-empty"><p>بانتظار إحداثيات GPS صالحة.<br>لن يُفترض موقع هدف من موقع الطائرة.</p></div></div><div class="map-legend"><span><b>●</b> الدرون: <bdi class="mono">${droneCoords(S.drone)?esc(coords(S.drone)):'غير متاح'}</bdi></span><span><b class="target">●</b> الهدف: <bdi class="mono">${targetCoords(selectedEvent())?esc(coords(selectedEvent())):'غير متاح'}</bdi></span><span>الخط: العينات المستلمة من مسار المهمة</span></div></section>`}
function dashboard(){return heading('MISSION CONTROL','لوحة المراقبة','الدليل المصوّر، القرار البشري، وحالة الطائرة في مساحة واحدة.',`<button data-nav="tracking">فتح التتبع ◎</button>`)+metrics()+`<div class="dashboard-grid"><div class="stack">${focusCard(selectedEvent())}${mapPanel()}</div><div class="stack">${queue()}<div class="sidebar-telemetry">${telemetry()}</div><div class="notice info">GPS الدرون يحدد موقع الطائرة. موقع الهدف يحتاج إحداثيات مستقلة أو تقديرًا من نظام الكشف، وتظهر صلاحيته كما أرسلها المصدر.</div></div></div>`}
function tracking(){return heading('POSITION & TELEMETRY','التتبع والموقع','عرض آخر موقع مستلم ومسار المهمة. القيم المتقادمة لا تعني اتصالًا حيًا.')+`<div class="panel panel-body body-row"><label>الطائرة<select id="drone-select">${S.drones.length?S.drones.map(d=>`<option value="${esc(d.drone_id)}" ${d.drone_id===S.droneId?'selected':''}>${esc(d.drone_id)}</option>`).join(''):'<option>لا توجد بيانات</option>'}</select></label><label>هدف على الخريطة<select id="target-select"><option value="">أحدث حدث</option>${S.recent.map(e=>`<option value="${esc(e.event_id)}" ${e.event_id===S.selected?'selected':''}>${esc(e.event_id)} · ${esc(label(e.object))}</option>`).join('')}</select></label><small>المسار يعرض آخر 600 عينة للمهمة المحددة.<br>الفجوات لأكثر من 30 ثانية لا تُوصل بخط.</small></div><div class="gap">${mapPanel(true)}</div><div class="gap">${telemetry()}</div>`}
function archive(){const f=S.filters;return heading('HISTORICAL RECORDS','الأرشيف','بحث في جميع الأحداث المحفوظة. مرشحات التاريخ بحسب UTC، وأوقات العرض بتوقيت جهازك.')+`<form id="filters" class="filters"><label>معرّف الحدث الكامل<input id="filter-id" value="${esc(f.id)}" placeholder="EVT-001" maxlength="160"></label><label>حالة المراجعة<select id="filter-status"><option value="">كل الحالات</option>${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${f.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>نوع الرصد<select id="filter-object"><option value="">كل الأنواع</option>${Object.entries(types).map(([k,v])=>`<option value="${k}" ${f.object===k?'selected':''}>${v}</option>`).join('')}</select></label><label>من · UTC<input id="filter-from" type="date" value="${f.from}"></label><label>إلى · UTC<input id="filter-to" type="date" value="${f.to}"></label><button class="primary">بحث</button></form><section class="panel"><div class="panel-head"><h2>سجل الأحداث</h2><small>${S.historyTotal} نتيجة</small></div>${table(S.history)}<div class="pagination"><span>الصفحة ${S.page+1} من ${Math.max(1,Math.ceil(S.historyTotal/20))}</span><div class="actions"><button id="previous" ${S.page===0?'disabled':''}>السابق</button><button id="next" ${(S.page+1)*20>=S.historyTotal?'disabled':''}>التالي</button></div></div></section>`}
function table(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>الحدث / المهمة</th><th>نوع الرصد</th><th>الثقة</th><th>وقت الكشف</th><th>صلاحية الموقع</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>${rows.map(e=>`<tr><td><span class="mono">${esc(e.event_id)}</span><small>${esc(e.mission_id)}</small></td><td>${esc(label(e.object))}${uncertain(e.object)?`<small class="uncertain">غير مؤكد</small>`:''}</td><td>${number(e.confidence==null?null:e.confidence*100)}%</td><td>${esc(time(e.timestamp))}</td><td>${esc(validity[e.location_validity])}</td><td>${pill(e.status)}</td><td><button data-open="${esc(e.event_id)}">فتح</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد أحداث مطابقة للبحث.</div>'}
function events(){return heading('EVENT LIBRARY','مرجع الأحداث','آخر 24 حدثًا مع الأدلة الأصلية. للوصول إلى السجل الكامل استخدم الأرشيف.',`<button data-nav="archive">فتح الأرشيف ↗</button>`)+`<details class="panel panel-body"><summary>دليل أنواع الرصد وحقول الحدث</summary><div class="glossary">${Object.entries(types).map(([k,v])=>`<div><h3>${v}</h3><code>${esc(k)}</code><p>${uncertain(k)||'تصنيف صادر من نظام الكشف، يحتاج مراجعة السياق.'}</p></div>`).join('')}<div><h3>إحداثيات الهدف</h3><p>latitude / longitude للهدف، منفصلتان عن drone_latitude / drone_longitude وقت الرصد. Valid صالح حسب المصدر، Approximate تقريبي، Unavailable غير متاح. HDOP ليس خطأ بالمتر.</p></div><div><h3>مهلة المراجعة</h3><p>20 ثانية تبدأ من استقبال الخادم. القرار يحفظ في قاعدة البيانات، ولا تعاد المهلة عند تحديث الصفحة.</p></div><div><h3>الثقة ووجود شخص</h3><p>الثقة قيمة بين 0 و1 تظهر كنسبة مئوية. person_visible=null يعني غير معروف، ولا يعني عدم وجود شخص.</p></div></div></details><div class="event-cards gap">${S.recent.map(e=>`<article class="panel">${media(e)}<div class="panel-body"><div class="card-top"><h2>${esc(label(e.object))}</h2>${pill(e.status)}</div><p><bdi class="mono">${esc(e.event_id)}</bdi><br>${esc(time(e.timestamp))}</p>${uncertain(e.object)?`<p class="uncertain">${uncertain(e.object)}</p>`:''}<button data-open="${esc(e.event_id)}">عرض بيانات الحدث ←</button></div></article>`).join('')||'<div class="panel empty">لم تُستلم أحداث بعد.</div>'}</div>`}
function detail(){const e=S.detail;if(!e||e.event_id!==route().id)return heading('EVENT DETAILS','تفاصيل الحدث','جارٍ جلب البيانات…');const fields=[['معرّف الحدث',e.event_id],['المهمة',e.mission_id],['الدرون',e.drone_id],['رقم التتبع',e.track_id],['نوع الرصد',label(e.object)],['الثقة',number(e.confidence==null?null:e.confidence*100)+'%'],['ظهور شخص',e.person_visible==null?'غير معروف':e.person_visible?'نعم حسب الكشف':'لا حسب الكشف'],['إحداثيات الهدف',targetCoords(e)?coords(e):'غير متاحة'],['صلاحية موقع الهدف',validity[e.location_validity]],['مصدر الموقع',sources[e.location_source||'unknown']],['دقة الهدف المبلغ عنها',e.target_accuracy_m==null?'غير متاحة':number(e.target_accuracy_m)+' م'],['موقع الدرون وقت الرصد',coords({latitude:e.drone_latitude,longitude:e.drone_longitude})],['وقت الكشف',time(e.timestamp)],['وقت الاستقبال',time(e.received_at)],['بداية المراجعة',time(e.review_started_at)],['نهاية المهلة',time(e.review_expires_at)],['وقت القرار',time(e.decision_time)],['صاحب القرار',e.operator_id],['إصدار النموذج',e.model_version],['إصدار السجل',e.version],['حالة التسليم',e.delivery_status],['صندوق الكشف',e.bbox?JSON.stringify(e.bbox):'غير متاح']];return heading('EVENT DETAILS',esc(e.event_id),'البيانات الأصلية والدليل المصوّر وسجل قرار المراجعة.',`<button data-nav="archive">الأرشيف</button><button id="locate-event">عرض الموقع ◎</button>`)+`<div class="details-grid"><div class="stack"><section class="panel">${media(e)}<div class="panel-body">${uncertain(e.object)?`<p class="uncertain">${uncertain(e.object)}</p>`:''}${review(e)}</div></section><details class="panel panel-body"><summary>عرض بيانات JSON</summary><pre class="json">${esc(JSON.stringify(e,null,2))}</pre></details></div><section class="panel"><div class="panel-head"><h2>بيانات الحدث</h2>${pill(e.status)}</div><dl class="detail-fields panel-body">${fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v??'غير متاح')}</dd></div>`).join('')}</dl></section></div>`}
function commands(){return heading('AUTHORIZED REQUESTS','الأوامر','الأوامر المسموحة من النظام المتصل فقط. تسجيل الطلب لا يعني تنفيذه.')+`<div class="notice ${freshness()?'info':''}">${freshness()?'بيانات الدرون حديثة. تحقق من سياق المهمة قبل إرسال أي طلب.':'بيانات الدرون غير متاحة أو متقادمة. إرسال الأوامر متوقف.'}</div><div class="commands">${S.commands.map(c=>`<section class="panel panel-body"><h2>${esc(c.label)}</h2><p>${esc(c.description||c.reason||'طلب يحتاج تحقق النظام المتصل')}</p><button data-command="${esc(c.code)}" ${!c.enabled||!freshness()||S.error?'disabled':''}>مراجعة الطلب</button></section>`).join('')||'<div class="panel empty">لم يعلن النظام المتصل عن أوامر مسموحة بعد.</div>'}</div><section class="panel gap"><div class="panel-head"><h2>آخر طلبات الأوامر</h2><small>حتى 25 طلبًا</small></div>${S.commandLog.length?`<div class="table-wrap"><table><thead><tr><th>الأمر</th><th>الحالة</th><th>الوقت</th><th>السبب / تأكيد التنفيذ</th></tr></thead><tbody>${S.commandLog.map(c=>`<tr><td>${esc(c.label||c.command)}</td><td>${esc(c.status)}</td><td>${esc(time(c.created_at))}</td><td>${esc(c.acknowledgement||c.reason)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد طلبات.</div>'}</section>`}
function admin(){if(S.profile.role!=='admin')return '<div class="notice error">هذا القسم يتطلب صلاحية مدير.</div>';return heading('WORKSPACE ADMINISTRATION','الإدارة','الحساب المدير يستخدم جميع أقسام الموقع من جلسة واحدة.',`<button id="test-event">إضافة حدث اختباري</button><button id="new-account" class="primary">إنشاء حساب مدير</button>`)+`<section class="panel"><div class="panel-head"><h2>حسابات مساحة العمل</h2><small>الصلاحيات محفوظة في الخادم</small></div><div class="table-wrap"><table><thead><tr><th>الاسم / معرّف الدخول</th><th>الصلاحية</th><th>الوصول</th><th>إجراء</th></tr></thead><tbody>${S.users.map(u=>`<tr><td>${esc(u.display_name)}<small class="mono">${esc(u.login_id||'لم يُربط ID بعد')}</small></td><td>${u.role==='admin'?'مدير':'مشغّل'}</td><td>${u.active?'مفعّل':'معطّل'}</td><td>${u.role==='admin'?'<small>يديره مالك النظام</small>':`<button data-access="${esc(u.id)}" data-active="${u.active?'false':'true'}">${u.active?'تعطيل':'تفعيل'}</button>`}</td></tr>`).join('')}</tbody></table></div></section><section class="panel gap"><div class="panel-head"><h2>سجل النشاط</h2></div>${S.audit.length?`<div class="table-wrap"><table><thead><tr><th>الوقت</th><th>العملية</th><th>الحدث</th><th>المنفذ</th></tr></thead><tbody>${S.audit.map(a=>`<tr><td>${esc(time(a.created_at))}</td><td>${esc(a.action)}</td><td>${esc(a.event_id)}</td><td>${esc(a.actor_id||'النظام')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا يوجد نشاط مسجل بعد.</div>'}</section>`}
function render(){if(!S.profile)return;const r=route();const oldMap=$('#map'),reuse=oldMap&&mapState&&['dashboard','tracking'].includes(r.name)&&mapState.route===r.name?oldMap:null;if(reuse)reuse.remove();else destroyMap();const active=document.activeElement;let focus=null;if(active?.id&&$('#view').contains(active)){focus={id:active.id,value:active.value,start:active.selectionStart,end:active.selectionEnd}}const views={dashboard,tracking,events,archive,commands,admin,event:detail};$('#view').innerHTML=views[r.name]();if(reuse&&$('#map')){$('#map').replaceWith(reuse);mapState.map.invalidateSize()}$('#connection-error').hidden=!S.error;$('#connection-error').textContent=S.error;$$('[data-nav]').forEach(b=>{const current=b.dataset.nav===r.name||(r.name==='event'&&b.dataset.nav==='events');b.classList.toggle('active',current);if(current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('#admin-nav').hidden=S.profile.role!=='admin';bind();updateTimers();updateConnection();void hydrateImages();if($('#map'))mountMap();if(focus){const el=document.getElementById(focus.id);if(el){el.value=focus.value;el.focus({preventScroll:true});if(typeof focus.start==='number')try{el.setSelectionRange(focus.start,focus.end)}catch{}}}}
function updateConnection(){if(!S.profile)return;const ok=S.lastSync&&!S.error&&Date.now()-S.lastSync<CONFIG.telemetryFreshMs;$('#connection-label').textContent=S.error?'الاتصال يحتاج متابعة':!S.lastSync?'بانتظار البيانات':ok?(S.ws?.readyState===1?'متصل · تحديثات فورية':'متصل · مزامنة كل 5 ثوانٍ'):'البيانات متقادمة';$('#connection-label').classList.toggle('good',!!ok);$('#last-sync').textContent=S.lastSync?'آخر مزامنة: '+time(S.lastSync):'لم تصل بيانات بعد'}
function updateTimers(){for(const box of $$('[data-review]')){const e=[...S.pending,...S.recent,S.detail].find(x=>x?.event_id===box.dataset.review);const r=remaining(e);box.querySelector('[data-timer]').textContent=r===null?'وقت غير متاح':r+' ثانية';box.querySelector('[data-progress]').style.width=(r===null?0:Math.min(100,r*5))+'%';box.querySelectorAll('[data-decision]').forEach(b=>b.disabled=!canReview(e));box.querySelector('[data-review-note]').textContent=S.busy.has(e?.event_id)?'جارٍ حفظ القرار…':r===0?'انتهت المهلة. بانتظار تأكيد الخادم.':S.error||Date.now()-S.lastSync>=CONFIG.telemetryFreshMs?'الاتصال غير مؤكد؛ المراجعة متوقفة مؤقتًا.':''}$$('[data-command]').forEach(b=>b.disabled=!freshness()||!!S.error||!S.commands.find(c=>c.code===b.dataset.command)?.enabled);updateConnection()}
async function hydrateImages(){const gen=S.generation;const ids=[...new Set($$('[data-image]').map(el=>el.dataset.image))];await Promise.all(ids.map(async id=>{try{let cache=S.media.get(id);if(!cache||cache.expires<Date.now()){const {data}=await api('/events/'+encodeURIComponent(id)+'/image');const url=new URL(data.signed_url);if(url.protocol!=='https:'||url.username||url.password)throw Error('Untrusted image URL');cache={url:url.href,expires:Date.now()+45000};S.media.set(id,cache);if(S.media.size>150)S.media.delete(S.media.keys().next().value)}if(gen!==S.generation)return;for(const box of $$('[data-image]').filter(el=>el.dataset.image===id)){if(box.querySelector('img'))continue;const img=new Image();img.alt='الصورة الأصلية للحدث '+id;img.referrerPolicy='no-referrer';img.onload=()=>box.querySelector('.media-message')?.remove();img.onerror=()=>{img.remove();const m=box.querySelector('.media-message');if(m)m.textContent='تعذر تحميل الصورة. استخدم تحديث لإعادة المحاولة.'};img.src=cache.url;box.append(img)}}catch{if(gen===S.generation)for(const box of $$('[data-image]').filter(el=>el.dataset.image===id)){const m=box.querySelector('.media-message');if(m)m.textContent='الصورة غير متاحة أو غير مسموح بقراءتها.'}}}))}
async function decide(id,decision){const e=[...S.pending,...S.recent,S.detail].find(e=>e?.event_id===id);if(!canReview(e))return;S.busy.add(id);updateTimers();try{await api('/events/'+encodeURIComponent(id)+'/decision',{method:'POST',body:JSON.stringify({decision,expected_version:e.version})});toast(decision==='accepted'?'حُفظ قرار القبول.':'حُفظ قرار الرفض.')}catch(e){toast(failure(e))}finally{S.busy.delete(id);await sync();updateTimers()}}
function bind(){for(const b of $$('[data-nav]'))b.onclick=()=>nav(b.dataset.nav);for(const b of $$('[data-open]'))b.onclick=()=>nav('event/'+encodeURIComponent(b.dataset.open));for(const b of $$('[data-select]'))b.onclick=()=>{S.selected=b.dataset.select;render()};for(const b of $$('[data-decision]'))b.onclick=()=>decide(b.dataset.id,b.dataset.decision);
 if($('#filters'))$('#filters').onsubmit=e=>{e.preventDefault();const f={id:$('#filter-id').value.trim(),status:$('#filter-status').value,object:$('#filter-object').value,from:$('#filter-from').value,to:$('#filter-to').value};if(f.from&&f.to&&f.from>f.to)return toast('تاريخ البداية يجب ألا يتجاوز تاريخ النهاية.');S.filters=f;S.page=0;void sync()};if($('#previous'))$('#previous').onclick=()=>{S.page--;void sync()};if($('#next'))$('#next').onclick=()=>{S.page++;void sync()};if($('#drone-select'))$('#drone-select').onchange=e=>{S.droneId=e.target.value;S.track=[];destroyMap();void sync()};if($('#target-select'))$('#target-select').onchange=e=>{S.selected=e.target.value||null;render();fitMap()};if($('#locate-event'))$('#locate-event').onclick=()=>{S.selected=S.detail.event_id;nav('tracking')};
 if($('#new-account'))$('#new-account').onclick=()=>{$('#account-form').reset();$('#account-error').textContent='';$('#account-dialog').showModal()};if($('#test-event'))$('#test-event').onclick=()=>{$('#test-form').reset();$('#test-id').value='TEST-'+Date.now();$('#test-error').textContent='';$('#test-dialog').showModal()};for(const b of $$('[data-access]'))b.onclick=async()=>{b.disabled=true;try{await api('/admin/users/'+encodeURIComponent(b.dataset.access),{method:'PATCH',body:JSON.stringify({active:b.dataset.active==='true'})});await sync()}catch(e){toast(failure(e));b.disabled=false}};for(const b of $$('[data-command]'))b.onclick=()=>{S.command=S.commands.find(c=>c.code===b.dataset.command);S.commandKey=crypto.randomUUID();S.commandPayload=null;$('#command-form').reset();$('#command-title').textContent=S.command.label;$('#command-error').textContent='';$('#command-dialog').showModal()};}
async function connectSocket(){if(!S.profile||!CONFIG.websocketEnabled)return;closeSocket();const gen=S.generation;try{const {data}=await api('/ws-ticket',{method:'POST',body:'{}'});if(gen!==S.generation)return;const url=new URL(API_BASE);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname='/api/v1/ws';url.search='';url.searchParams.set('ticket',data.ticket);const ws=new WebSocket(url);S.ws=ws;ws.onopen=()=>{updateConnection();void sync()};ws.onmessage=message=>{try{const m=JSON.parse(message.data);if(['event.created','event.updated','telemetry.updated','command.updated','access.updated'].includes(m.type))void sync()}catch{}};ws.onclose=()=>{updateConnection();if(S.profile&&gen===S.generation)S.wsRetry=setTimeout(connectSocket,3000)};ws.onerror=()=>ws.close()}catch{if(S.profile&&gen===S.generation)S.wsRetry=setTimeout(connectSocket,5000)}}
function destroyMap(){if(mapState){mapState.map.remove();mapState=null}}
function fitMap(){if(!mapState)return;const bounds=mapState.layers.getBounds();if(bounds.isValid())mapState.map.fitBounds(bounds.pad(.18),{maxZoom:16,animate:false})}
function mountMap(){if(!mapState){const map=L.map('map',{attributionControl:true,zoomControl:true,worldCopyJump:true}).setView([0,0],2);mapState={map,layers:L.featureGroup().addTo(map),route:route().name,tiles:null,first:true};L.control.scale({imperial:false}).addTo(map)}const m=mapState;m.layers.clearLayers();const d=S.drone,e=selectedEvent();let count=0;
 const marker=(lat,lon,color,title)=>{const text=document.createElement('span');text.textContent=title;L.circleMarker([lat,lon],{radius:9,color:'#09151c',weight:3,fillColor:color,fillOpacity:1}).bindTooltip(text).addTo(m.layers);count++};
 if(droneCoords(d))marker(d.latitude,d.longitude,freshness()?'#70e0cc':'#899fa8',(freshness()?'الدرون':'آخر موقع للدرون · متقادم')+' '+d.drone_id);
 if(targetCoords(e)){marker(e.latitude,e.longitude,'#efc580','الهدف '+e.event_id+' · '+validity[e.location_validity]);if(e.target_accuracy_m!=null&&e.target_accuracy_m>0)L.circle([e.latitude,e.longitude],{radius:e.target_accuracy_m,color:'#efc580',fillOpacity:.08,weight:1}).addTo(m.layers)}
 let segment=[],previous=null;const flush=()=>{if(segment.length>1)L.polyline(segment,{color:'#70e0cc',weight:2,opacity:.55}).addTo(m.layers);segment=[]};for(const p of S.track){if(!droneCoords(p)){flush();previous=null;continue}if(previous&&(Date.parse(p.updated_at)-Date.parse(previous.updated_at)>30000||Math.abs(p.longitude-previous.longitude)>180))flush();segment.push([p.latitude,p.longitude]);previous=p}flush();
 $('#map-empty').hidden=count>0;$('#map-center').onclick=fitMap;$('#map-basemap').textContent=m.tiles?'إخفاء خريطة الشوارع':'تحميل خريطة الشوارع';$('#map-note').textContent=m.tiles?'الخلفية من OpenStreetMap؛ يتم طلب صور منطقة العرض عبر الإنترنت.':'الإحداثيات تعمل دون تحميل خلفية خارجية.';
 $('#map-basemap').onclick=()=>{if(m.tiles){m.map.removeLayer(m.tiles);m.tiles=null;mountMap();return}if(!CONFIG.mapTileUrl.startsWith('https://'))return toast('مصدر خريطة غير صالح.');m.tiles=L.tileLayer(CONFIG.mapTileUrl,{maxZoom:19,attribution:CONFIG.mapAttribution,referrerPolicy:'strict-origin-when-cross-origin'}).addTo(m.map);m.tiles.on('tileerror',()=>{$('#map-note').textContent='تعذر تحميل خلفية الخريطة. علامات GPS تبقى متاحة.'});mountMap()};if(count&&m.first){fitMap();m.first=false}}
$('#login-form').onsubmit=login;$('#mfa-form').onsubmit=verifyMfa;$('#toggle-password').onclick=()=>{const p=$('#login-password');p.type=p.type==='password'?'text':'password';$('#toggle-password').textContent=p.type==='password'?'إظهار':'إخفاء'};$('#mfa-cancel').onclick=async()=>{if(S.enrollment)try{await authRequest('factors/'+encodeURIComponent(S.enrollment),undefined,'DELETE')}catch{}await logout()};$('#logout').onclick=logout;$('#refresh').onclick=()=>{S.media.clear();void sync()};for(const b of $$('[data-close]'))b.onclick=()=>{document.getElementById(b.dataset.close).close();$('#account-password').value=''};
$('#command-form').onsubmit=async e=>{e.preventDefault();if(!freshness()||S.error){$('#command-error').textContent='بيانات الطائرة متقادمة أو الاتصال غير مؤكد.';return}$('#command-send').disabled=true;try{S.commandPayload??={command:S.command.code,reason:$('#command-reason').value.trim(),drone_id:S.drone.drone_id,mission_id:S.drone.mission_id,telemetry_timestamp:S.drone.updated_at};await api('/commands',{method:'POST',headers:{'Idempotency-Key':S.commandKey},body:JSON.stringify(S.commandPayload)});$('#command-dialog').close();S.command=null;S.commandPayload=null;toast('سُجل الطلب. انتظر تأكيد التنفيذ من النظام المتصل.');await sync()}catch(error){$('#command-error').textContent=failure(error)+' إعادة المحاولة تستخدم الطلب نفسه.'}finally{$('#command-send').disabled=false}};
$('#account-form').onsubmit=async e=>{e.preventDefault();$('#account-send').disabled=true;try{await api('/admin/users',{method:'POST',body:JSON.stringify({login_id:$('#account-id').value.trim(),display_name:$('#account-name').value.trim(),email:$('#account-email').value.trim(),password:$('#account-password').value,role:'admin'})});$('#account-dialog').close();$('#account-form').reset();toast('أُنشئ الحساب. يلزمه إعداد Authenticator عند أول دخول.');await sync()}catch(error){$('#account-error').textContent=failure(error)}finally{$('#account-password').value='';$('#account-send').disabled=false}};
$('#test-form').onsubmit=async e=>{e.preventDefault();$('#test-send').disabled=true;try{const image=$('#test-image').files[0];if(image&&image.size>10*1024*1024)throw Error('حجم الصورة يتجاوز 10 MiB.');const payload={event_id:$('#test-id').value.trim(),mission_id:'MIS-TEST',track_id:1,object:$('#test-object').value,person_visible:null,confidence:null,latitude:null,longitude:null,location_validity:'Unavailable',timestamp:new Date().toISOString(),image_path:null,status:'pending'};const form=new FormData();form.append('event_json',JSON.stringify(payload));if(image)form.append('image',image);await api('/admin/events/upload',{method:'POST',body:form});$('#test-dialog').close();S.selected=payload.event_id;nav('dashboard');await sync();toast('حُفظ الحدث الاختباري. بدأت نافذة المراجعة.')}catch(error){$('#test-error').textContent=failure(error)}finally{$('#test-send').disabled=false}};
window.addEventListener('hashchange',()=>void navigate());window.addEventListener('offline',()=>{S.error='انقطع اتصال الإنترنت. القرارات متوقفة حتى عودة الاتصال.';if(S.profile)render()});window.addEventListener('online',()=>void sync());setInterval(updateTimers,250);setInterval(()=>{if(S.profile)void sync()},CONFIG.pollIntervalMs);
